#!/bin/zsh
# Install the daily run as a launchd agent.
#
# launchd rather than cron because it survives sleep (it fires on wake if the
# window was missed) and inherits the login Keychain, which `twitter` needs to
# decrypt Chrome's cookie store. A cron job started outside a login session is
# the classic way to get "Keychain permission denied" at 07:00.
#
#   ./install-cron.sh          install and load
#   ./install-cron.sh remove   unload and delete

set -euo pipefail

ROOT="${0:A:h}"
LABEL="com.tanmay.xsignaltracker"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
HOUR=7
MINUTE=0

# --force skips the TCC guard below, for when Full Disk Access has been granted.
FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

if [[ "${1:-}" == "remove" ]]; then
  launchctl unload "$PLIST" 2>/dev/null || true
  rm -f "$PLIST"
  echo "removed $LABEL"
  exit 0
fi

mkdir -p "$HOME/Library/LaunchAgents" "$ROOT/out"

# macOS TCC protects ~/Desktop, ~/Documents and ~/Downloads from unattended
# launchd agents. `ls` succeeds (metadata) but reading the file returns
# "Operation not permitted", which surfaces as a baffling
# "can't open input file". Detected here rather than left to fail at 07:00.
case "$ROOT" in
  "$HOME/Desktop"/*|"$HOME/Documents"/*|"$HOME/Downloads"/*)
    if [[ $FORCE -eq 1 ]]; then
      echo "WARNING: $ROOT is TCC-protected; installing anyway (--force)."
      echo "         Full Disk Access must be granted to /usr/bin/caffeinate,"
      echo "         or the 07:00 run fails with 'Operation not permitted'."
      echo
    else
      echo "REFUSING TO INSTALL: $ROOT is inside a TCC-protected folder."
      echo
      echo "launchd cannot read files there without Full Disk Access, so the job"
      echo "would fail every morning with 'Operation not permitted'."
      echo
      echo "Two fixes:"
      echo "  1. Move the project out, e.g. to ~/financial-tracker. This is what"
      echo "     ~/jobbot already does, and it needs no system permissions."
      echo "  2. Grant Full Disk Access to /usr/bin/caffeinate:"
      echo "       System Settings > Privacy & Security > Full Disk Access > +"
      echo "       press Cmd+Shift+G, type /usr/bin/caffeinate, Open, toggle ON"
      echo "     Then re-run:  ./install-cron.sh --force"
      exit 1
    fi
    ;;
esac

# The launcher must live OUTSIDE the TCC-protected folder. Exec'ing a script
# that itself sits on the Desktop loses Full Disk Access inheritance -- uv then
# fails with "failed to open pyproject.toml: Operation not permitted" even
# though FDA is granted to caffeinate. A launcher in ~/.local/bin reads the
# Desktop project fine; verified directly.
LAUNCHER_DIR="$HOME/.local/bin"
LAUNCHER="$LAUNCHER_DIR/xsignal-run.sh"
mkdir -p "$LAUNCHER_DIR"

# The launcher inlines the run rather than calling run-daily.sh, because
# *executing* a script that lives on the Desktop is what loses Full Disk Access
# — a launcher outside the protected folder can read the project fine, but the
# moment it exec's the Desktop copy, uv fails with
# "failed to open pyproject.toml: Operation not permitted".
# run-daily.sh remains the manual entry point; this is the scheduled twin.
cat > "$LAUNCHER" <<LAUNCHEOF
#!/bin/zsh
# Generated by install-cron.sh — do not edit. Lives outside ~/Desktop for TCC.
set -uo pipefail
ROOT="$ROOT"
LOG="\$ROOT/out/run.log"
mkdir -p "\$ROOT/out"
export TWITTER_BROWSER=chrome
export TWITTER_CHROME_PROFILE=Default
[[ -f "\$ROOT/.env" ]] && source "\$ROOT/.env"
cd "\$ROOT" || exit 1
{
  echo "=== \$(date '+%Y-%m-%d %H:%M:%S') ==="
  uv run python src/run.py
  echo "exit: \$?"
} 2>&1 | tee -a "\$LOG"
STATUS=\${pipestatus[1]}
if [[ \$STATUS -ne 0 ]]; then
  MSG="X Signal Tracker FAILED \$(date '+%d %b %H:%M'). Page left untouched. See out/run.log"
  if [[ -n "\${TELEGRAM_BOT_TOKEN:-}" && -n "\${TELEGRAM_CHAT_ID:-}" ]]; then
    curl -s -X POST "https://api.telegram.org/bot\${TELEGRAM_BOT_TOKEN}/sendMessage" \\
      -d "chat_id=\${TELEGRAM_CHAT_ID}" -d "text=\${MSG}" >/dev/null
  fi
  osascript -e "display notification \"\$MSG\" with title \"X Signal Tracker\"" 2>/dev/null
fi
exit \$STATUS
LAUNCHEOF
chmod +x "$LAUNCHER"

cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <!-- No shell operators here: '&' is reserved in XML, so an inline
       "cd ... && ./run-daily.sh" corrupts the plist and launchd ends up trying
       to open the script as an input file. WorkingDirectory does the cd.
       caffeinate -i keeps the Mac awake for the ~5 min the run takes, matching
       the com.tanmay.jobbot.* agents. -->
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/caffeinate</string>
    <string>-i</string>
    <string>$LAUNCHER</string>
  </array>
  <key>WorkingDirectory</key><string>$ROOT</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$HOME/.nvm/versions/node/v22.22.3/bin:$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>$HOUR</integer>
    <key>Minute</key><integer>$MINUTE</integer>
  </dict>
  <key>StandardOutPath</key><string>$ROOT/out/launchd.log</string>
  <key>StandardErrorPath</key><string>$ROOT/out/launchd.err</string>
  <key>RunAtLoad</key><false/>
</dict>
</plist>
PLISTEOF

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

echo "installed $LABEL — runs daily at $(printf '%02d:%02d' $HOUR $MINUTE) local time"
echo
echo "verify:   launchctl list | grep xsignaltracker"
echo "run now:  launchctl start $LABEL"
echo "logs:     tail -f '$ROOT/out/run.log'"
echo "remove:   ./install-cron.sh remove"
echo
echo "NOTE: the first scheduled run is the real test of Keychain access from a"
echo "non-interactive context (spec Phase 5a). If out/run.log shows"
echo "'not_authenticated', the fallback is explicit TWITTER_AUTH_TOKEN and"
echo "TWITTER_CT0 in a chmod 600 .env file."
